### ISSUE TITLE
Get download stats by author doesn't work anymore

### ISSUE THREAD

**Issue by christian-bromann** [pvorb/npm-stat.com#58]
If you select "Author" in the dropdown npm-stat is not able anymore to get stats by author. It says:

```
Could not fetch data. Does that package exist? Case matters.
feign.FeignException: status 404 reading
AuthorsClient#browseAuthors(String,String); content:
```

Url is https://npm-stat.com/charts.html?author=<username>&from=2017-05-16&to=2018-05-16

**Comment by pvorb** [comment]
npm-stat.com used to query the npm registry in order to get all packages of an author (e.g. https://registry.npmjs.org/-/_view/browseAuthors?group_level=2&start_key=pvorb&end_key=pvorb). As you can probably see, this API is pretty much implementation specific.

The request no longer works and I have no idea if there is another way to get all packages by an author, but I also didn't invest much time into finding one. If somebody knows how to do this, I'd appreciate a hint and I'll fix this.

**Comment by kanekotic** [comment]
so you could ask @matteofigus still can get stats for all packages https://github.com/matteofigus/npm-stats-www

**Comment by pvorb** [comment]
@kanekotic Thanks for pointing me into the right direction. I looked into the implementation, which is using the package "npm-stats" and changed to the CouchDB view that is used in that package.

So, finally, author stats are working again! :tada:

**Comment by kanekotic** [comment]
@pvorb you're welcome I just pass a repo, you did the awesome job of implementing it 😄
Thanks a lot for the great project

**Comment by kanekotic** [comment]
@pvorb seems this is starting to happen again
